#theme: jekyll-theme-minimal
remote_theme: poole/hyde
title: Carlos Romero Blázquez
description: PhD Student in Economics at LMU Munich
logo: assets/img/carlos.jpeg
contact: Carlos.Romero@econ.lmu.de
