theme: jekyll-theme-minimal
title: Carlos Romero Blázquez
description: PhD Student in Economics at LMU Munich
#logo: assets/img/carlos.jpeg
logo: assets/img/LMU_2026-04-22_5711.jpg
contact: Carlos.Romero@econ.lmu.de
